services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: bookvault
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  cdn:
    image: nginx:alpine
    ports:
    - 1350:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../uploads:/var/www/uploads
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:3.8
    container_name: localstack_container
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION= ap-south-2
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init/aws/init-localstack.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  postgres_data:
  localstack_data:

