// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/deepakgudla/bookvault/internal/dto"
)

type Mutation struct {
}

type OrderConnection struct {
	Edges    []*OrderEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type OrderEdge struct {
	Node *dto.OrderResponse `json:"node"`
}

type PageInfo struct {
	Page       int `json:"page"`
	Limit      int `json:"limit"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

type ProductConnection struct {
	Edges    []*ProductEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ProductEdge struct {
	Node *dto.ProductResponse `json:"node"`
}

type Query struct {
}

type UpdateProductInput struct {
	CategoryID  uint    `json:"category_id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int     `json:"stock"`
	IsActive    *bool   `json:"is_active,omitempty"`
}
